defaults: &defaults
  adapter: mysql
  host: localhost

<%= 
    file = File.join(Rails.root.to_s, "config", "dev_db_login.yml")
    IO.read(file) if File.exist?(file)
%>

development:
  <<: *defaults
  <<: *dev_login
  database: quizdash_dev

production:
  database: quizdash_prod